# Generated by Django 3.2.8 on 2021-12-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelApp.country'),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelApp.user'),
        ),
    ]
