# Generated by Django 3.2.8 on 2021-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_auto_20211211_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
