# Generated by Django 3.2.8 on 2021-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_auto_20211211_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'traveler',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
